name: Latest PaperMC

on:
  # Trigger every Wednesday at 2 AM UTC
  schedule:
    - cron: '0 2 * * 3'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Generate build arguments
      run: |
        set -euo pipefail
        ./paper-latest.sh

    - name: Build and push the Docker image
      run: |
        set -euo pipefail
        source .buildargs

        docker build \
          --build-arg PAPER_URL="${PAPER_URL}" \
          --build-arg SHA256="${SHA256}" \
          --build-arg JVM_FLAGS="${JVM_FLAGS}" \
          -t ghcr.io/florke-smp/paper:latest \
          -t ghcr.io/florke-smp/paper:${LATEST_VERSION} \
          -t ghcr.io/florke-smp/paper:${LATEST_VERSION}-${LATEST_BUILD} \
          .

        docker push ghcr.io/florke-smp/paper:latest
        docker push ghcr.io/florke-smp/paper:${LATEST_VERSION}
        docker push ghcr.io/florke-smp/paper:${LATEST_VERSION}-${LATEST_BUILD}
    
    - name: Docker system prune
      run: docker system prune -f
